id = "blade"
version = "0.1.0"
namespace = "com.github.bottlemc.blade"

[listeners]
initialize = [
    "BladeInitializeListener"
]
sheet = [
    "BladeSheetListener"
]

[environment]
    [environment.has]
    client = "*"
    molten = ">=0.1.0"